### ISSUE TITLE
TexasDIS metadata importance

### ISSUE THREAD

**Issue by dhardestylewis** [TexasDIS/metadata#6]
TexasDIS metadata importance

Levels of importance for metadata, could be by:
- outside standard / intuition (ArcGIS, QGIS, FGDC standard orders)
- urgency
- necessity

paginated / levelled as follows:
- mandatory
- conditionally mandatory
- optional

**Comment by lamfletcher** [comment]
We also need to think through which metadata fields correspond to the varying levels of metadata as we conceptualize them (e.g. which fields correspond to Level 1 metadata, which to Level 2, etc.) so that we can begin identifying what if anything we need to add or change to generate, e.g. Level 3 metadata.
